### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by Alruta** [yub18/DESSERT#1]
Hello,
I am interested in use this framework in my probing data but I am having some doubts and problems.

First, my data has some NAs on it and I don,t know if it will be a problem for the program. Until now, I have been testing changing the NAs to 0 but it's not the best so my question is if the program can manage the NAs.

The other question is if the program can manage with data from SHAPE-MaP. This structure probing method is not mentioned on your paper so maybe this is the reasson that explain that I get this error when I try to normalize the data:
merge transcripts
normalize to [0,1]
Error in FUN(if (length(d.call) < 2L) newX[, 1] else array(newX[, 1L],  : 
  Extreme reactivities. Perform corresponding quality control first.

I think that I can skip the normalization step, but when I try to do scan without normilize I get this error:
Scan ====================
sampling null ...
Error in sample.int(length(x), size, replace, prob) : 
  invalid 'size' argument

I would really appreciate if you could help me. Thank you very much

I can provide you with the data that I am using as imput and the commands I am using to test DiffScan.
Data: [https://github.com/Alruta/DiffScan_data_test.git](https://github.com/Alruta/DiffScan_data_test.git)
Code:
```
DATA = list(Data = tibble(VITRO1 = DATA$VITRO_1, VITRO2 = DATA$VITRO_2,
                                           VIVO1 = DATA$VIVO_1, VIVO2 = DATA$VIVO_2))

Initiation = init(DATA, qc_ctrl = F, ncores = 1)

Norm = normalize(Initiation, ncores = 1)

res = scan(DATA, seed = 123, alpha = 0.05, ncores = 1)
```

Thank you again!

**Comment by yub18** [comment]
Thank you for considering using DiffScan in your research. It seems that the data page https://github.com/Alruta/DiffScan_data_test.git is not available.

**Comment by Alruta** [comment]
Try now, It was in private. Sorry for that.

**Comment by yub18** [comment]
The condition names should be A1, A2, B1, B2. Try this:
`names(DATA) = c('A1', 'A2', 'B1', 'B2');
r = list(RNA1 = tibble(DATA))`
If your data has NA for a few nucleotide positions (for example, 7-10), remove these positions using 
`Initiation = init(r, qc_ctrl = list(bad_sites=list(RNA1 = 7:10)), ncores = 1)`
Or you may impute your reactivities first if it is an essential problem (https://www.nature.com/articles/s42256-021-00412-0).

**Comment by Alruta** [comment]
Ok, I think that now it is working correctly. THnak you very much for the fast answer!!

I will check the paper you have send. Thanks again!
