### ISSUE TITLE
Error in download.file(url = "https://cloud.tsinghua.edu.cn/f/fea1d50f36d44c01b812/?dl=1",  : 

### ISSUE THREAD

**Issue by MaxHuang1999** [yub18/DESSERT#2]
这里是有什么特殊的参数么，您提供的网址已经无法打开了。
![image](https://github.com/yub18/DiffScan/assets/99959011/084edf64-de97-4527-934e-992d1aa8ee62)
![image](https://github.com/yub18/DiffScan/assets/99959011/fa917f36-73f0-4c8b-b166-eb857d779e12)

**Comment by yub18** [comment]
谢谢，已更新。

**Comment by wangyuxianglulu** [comment]
> 谢谢，已更新。

您好，您提供的网站还是不能打开，需要如何解决呀

**Comment by yub18** [comment]
您现在试下呢？谢谢。
